apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: devops-ns
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: {{ .Values.labels_name }}
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000
